#!/usr/bin/env bash
# script that will display information about subdomains
if [ $# -eq 1 ]; then
    for subs in www lb-01 web-01 web-02; do
        RECORD="$(dig "$subs"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
        IP="$(dig "$subs"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
        echo "The subdomain $subs is a $RECORD record and points to $IP"
    done
elif [ $# -eq 2 ]; then 
    RECORD="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    IP="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $2 is a $RECORD record and points to $IP"
fi
