#!/usr/bin/env bash
# Install and configure HAproxy on server 

sudo apt-get update 
sudo apt-get install Nginx -y
sudo apt-get install haproxy
#append to back of haproxy file
sudo sed -i '\$aENABLED=1/' /etc/default/haproxy
frontend='frontend http_front\n\tbind *:80\n\tdefault_backend http_back\n'
backend='backend web-backend http_back\n\troundrobin\n\tserver 346-web-01 35.237.190.7:80 check\n\tserver 346-web-02 35.237.76.113:80 check\n'
sudo sed -i '\$a$frontend\n$backend' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
