#!/usr/bin/env bash
#display 'bad luck' for 4th, 'good luck' for 8th, 'Holberton School' otherwise
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$((i + 1))
done
