#!/usr/bin/env bash
#displays numbers from 1 to 20, bad luck from China on 4th, bad luck from Japan on 9th, bad luck from Italy on 17th
i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in 
    "4") echo "bad luck from China"
    ;;
    "9") echo "bad luck from Japan"
    ;;
    "17") echo "bad luck from Italy"
    ;;
    esac
    i=$((i + 1))
done
