#!/usr/bin/env bash
# configures new Ubuntu machine with settings

sudo apt-get update -y
sudo apt-get install Nginx -y
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
