#!/usr/bin/env bash
# configure server so that /redirect_me to another site 

sudo apt-get update
sudo apt-get install Nginx -y
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
redirect="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"
sudo sed -i "30i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
